[profile.default]
evm_version = "shanghai"       # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
test = "test"
cache_path = "cache_forge"
optimizer = true
optimizer_runs = 10_000
auto_detect_solc = true

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
localhost = "https://rpc.vnet.tenderly.co/devnet/grimmace/f960abaf-b453-470d-860c-630abffaa755"
goerli = "https://goerli.drpc.org/"
mainnet = "https://eth-mainnet.nodereal.io/v1/3d6510db1f7e49d5a4c644bd969aafeb"
